#Variaveis
NAME = rush-02
CFLAGS = -Wall - Wextra -Werror
FILES = *.c

#Script de compilação
all:
	gcc $(CFLAGS) -o $(NAME) $(FILES)

fclean:
	rm -f $(NAME)

#modelo
#targets: prerequisites
#	command
#	command
#	command
